-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfteumdasga+uDOwa
m/UrvZcViX1cpNb/A5D/60KmFyigCgYIKoZIzj0DAQehRANCAAQjtA9EmPNONHTw
hnUSmc21b2kJqVbL9O246i80eUm+flt8jjir6dmIMCuss1AeXpfGGVaLxj+Fgkxa
kTauHadm
-----END PRIVATE KEY-----